version: "3"

networks:
  keycloak-network:
    name: keycloak-network
    attachable: true

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:11.0.2
    command: ["-Djboss.http.port=9090"]
    ports:
      - "9090:9090"
    networks:
      - keycloak-network
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  nginx-report-server:
    container_name: nginx-report-server
    image: nginx
    networks:
      - keycloak-network
    volumes:
      - ./reports:/usr/share/nginx/html

  nginx:
    container_name: nginx
    image: evry/oidc-proxy
    ports:
      - "80:80"
    networks:
      - keycloak-network
    environment:
      - OID_DISCOVERY=http://keycloak:9090/auth/realms/master/.well-known/openid-configuration
      - OID_CLIENT_ID=nginx
      - OID_CLIENT_SECRET=86c03fda-457f-44a4-923c-7b1aeaddd625
      - OID_REDIRECT_PATH=/redirect_uri
      - OID_SESSION_SECRET=623q4hR325t36VsCD3g567922IC0073T
      - OID_SESSION_CHECK_SSI=off
      - OID_SESSION_NAME=session
      - PROXY_HOST=nginx-report-server
      - PROXY_PORT=80
      - PROXY_PROTOCOL=http
    volumes:
      - ./logs:/usr/local/openresty/nginx/logs
