CREATE TABLE application (
    id         SERIAL        PRIMARY KEY,
    name       VARCHAR (512) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);